#numpy tutorial link: https://www.youtube.com/watch?v=GB9ByFAIAH4 

Lists: slow
- size(4B), ref count(8B), obj type(8B), obj value(8B)
- pointer that uses random space for memory

Numpy: fast; uses fixed type
- 5 = 0000... 0101 (int32=4B)
- no need for type checking through objects
- uses contiguous memory -> SIMD vector processing & effective cache utilization
- MATLAB replacements (also scipy)
- Matplotlib, pandas, digital photography ..
- Machine learning (often deal with tensor)

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
print(a)
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[1 2 3]
[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
print(a.ndim)
print(b.ndim)

1
2


In [ ]:
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [ ]:
print(a.dtype)
aa = np.array(a, dtype='int16') # if u wanna be efficient
print(aa.dtype)
print(b.dtype)

int64
int16
float64


In [ ]:
print(a.itemsize) # 8 b/c int 64
print(b.itemsize)

8
8


In [ ]:
print(a.size)
# get total size
print(a.size * a.itemsize)
print(a.nbytes) # 3 elems, 8B
print(b.nbytes) # 6 elems, 8B

3
24
24
48


In [ ]:
print(a.itemsize)
b = np.array([1.0, 2, 3], dtype='int')
print(b.dtype)

8
int64


Accesssing / Changing specific elements, rows, columns, etc.

In [ ]:
c = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 9, 10, 11, 12, 13, 14]])
print(c)
print(c.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [ ]:
# get a specific element [r, c]
print(c[1, 3]) # 11
print(c[1, -4]) # 11

11
11


In [ ]:
# get a specific row
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# get a specific col
c[:, 2]

array([ 3, 10])

In [ ]:
c[0:2, 1:4]

array([[ 2,  3,  4],
       [ 9, 10, 11]])

In [ ]:
c[[0, 1],[4, 2]] # array([ 5, 10])

array([ 5, 10])

In [ ]:
# [startindex:endindex:stepsize]
print(c[1, 1:6:2]) #array([ 9, 11, 13])
print(c[1, 1:-1:2])

[ 9 11 13]
[ 9 11 13]


In [ ]:
c[1,5] = 20
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
c[0, 1:4] = 9
print(c)

[[ 1  9  9  9  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
d = np.array([[[1, 2],[3, 4]],[[5, 6],[7, 8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
d[0, 1, 1]

4

In [ ]:
d[:,0,:] = [[9,9],[9,9]]
print(d)

[[[9 9]
  [3 4]]

 [[9 9]
  [7 8]]]


Initialize different types of arrays

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
e = np.ones((2, 2), dtype='int32')
print(e)

[[1 1]
 [1 1]]


In [ ]:
np.full((3, 2), 20)

array([[20, 20],
       [20, 20],
       [20, 20]])

In [ ]:
print(np.full_like(e, 4)) # [[4, 4], [4, 4]]
print(np.full_like(e.shape, 4)) # e.shape:(2, 2) -> shape:(2,) -> [4, 4]

[[4 4]
 [4 4]]
[4 4]


In [ ]:
np.random.rand(4,2)

array([[0.45793174, 0.35115461],
       [0.09576198, 0.95839484],
       [0.24262945, 0.33402755],
       [0.39295329, 0.32379056]])

In [ ]:
np.random.randint(7)

3

In [ ]:
np.random.randint(-4, 7, size=(3,3))

array([[ 4, -2,  2],
       [ 1,  6,  0],
       [-3, -2,  0]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
f = np.array([1, 2, 3])
print(np.repeat(f, 3))
f = np.array([[1, 2, 3]])
print(np.repeat(f, 3))
print(np.repeat(f, 3, axis=0))

[1 1 1 2 2 2 3 3 3]
[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
output = np.ones([5, 5])
z = np.zeros([3, 3])
z[1,1] = 9
print(z)
output[1:-1, 1:-1] = z
print(output)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


#Be careful when copying arrays!!

In [ ]:
g = np.array([1, 2, 3])
h = g
h[0] = 10
print(g)

[10  2  3]


In [ ]:
# To prevent it, use copy()
g = np.array([1, 2, 3])
h = g.copy()
h[0] = 10
print(g)

[1 2 3]


Mathematics

In [ ]:
i = np.array([1, 2, 3, 4])
print(i + 3)
print(i * 2)
print(i / 2)
print(i ** 2)
print(np.sin(i))
print(np.cos(i))
print("np.tan(i)\n",np.tan(i))
print("np.sin(i) / np.cos(i)\n",np.sin(i) / np.cos(i))
i += 2
print(i)
# for more, look up https://numpy.org/doc/stable/reference/routines.math.html 

[4 5 6 7]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
np.tan(i)
 [ 1.55740772 -2.18503986 -0.14254654  1.15782128]
np.sin(i) / np.cos(i)
 [ 1.55740772 -2.18503986 -0.14254654  1.15782128]
[3 4 5 6]


Linear Algebra

In [ ]:
j = np.ones((2, 3))
print(j)

k = np.full((3,2), 2)
print(k)

print(np.matmul(j,k))
print(np.dot(j,k)) # if two 2Ds, dot == matmul

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]
[[6. 6.]
 [6. 6.]]


In [ ]:
l = np.identity(3)
np.linalg.det(l)

1.0

determinant: How much are areas/volumes scaled? & orientation inverted?

For more, visit https://numpy.org/doc/stable/reference/routines.linalg.html 

Statistics

In [ ]:
stats = np.array([[1, 2, 3],[4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)

In [ ]:
np.max(stats, axis=1)

array([3, 6])

In [ ]:
np.min(stats, axis=0)

array([1, 2, 3])

In [ ]:
np.sum(stats)

21

In [ ]:
print(np.sum(stats, axis = 0))
print(np.sum(stats, axis = 1))

[5 7 9]
[ 6 15]


Reorganizing arrays

In [ ]:
before = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(before)
after = before.reshape([4,2])
print(after)
after2 = before.reshape([2,2,2])
print(after2)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [ ]:
#Horizontally stacking vectors
h1 = np.ones([2, 4])
h2 = np.zeros([2, 2])
np.hstack([h2, h1, h2])

array([[0., 0., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 0., 0.]])

Miscellaneous

In [ ]:
 # Load data from file (w/o pandas)